sudo: required
services:
  - docker
language: java
jdk:
  - oraclejdk8
script:
  - mvn -Pdocker clean verify
addons:
 - googlechrome
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start