sudo: required
dist: trusty

services:
  - docker

language: java
jdk:
  - oraclejdk8

script:
  - export MAVEN_SKIP_RC=true
  - export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=512m"
  - "export PATH=`pwd`/bin:$PATH"
  - echo $HOME
  - mvn -Pdocker clean test
